trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Match Node.js version with your app requirements
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build  # Assumes "build" script is defined in package.json
  displayName: 'Install Dependencies and Build Project'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist'  # Replace with your build output directory if different
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Archive Build Artifacts'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'az_react_test' 
    appName: '<simplereactapp>'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
  displayName: 'Deploy to Azure Web App'
